### ISSUE TITLE
P2P Networking Layer (Airbloc Network)

### ISSUE THREAD

**Issue by therne** [airbloc/airbloc-go#13]
a.k.a. **Airbloc Network**

## Purpose

* Exchange 과정에서의 Re-Encryption Key 요청 및 공유
* Identity Matching
* Data Index Sync 과정의 단축? (Mentioned in #4 )
* Interactive Challenges (ex: Data Availability Challenge)

## Requirements

- [libp2p](https://github.com/libp2p/go-libp2p) 사용
    * Encrypted Channel 지원
    * [Kademila DHT](https://github.com/libp2p/go-libp2p-kad-dht)
- Protocol Definition using Protobuf
    * [Prysm의 Protobuf를 이용한 p2p / rpc 인터페이스 정의 샘플 참고](https://github.com/prysmaticlabs/prysm/tree/master/proto)
- Abstractness: 어디에서든 간편하게 쓸 수 있어야 함. (LocalDatabase 인터페이스처럼!)

## Research Needed

 * TCP Transport vs QUIC Transport
 * Node Discovery 및 Identification Rule을 어떻게 할 것인가?
     * e.g) [DevP2P](https://github.com/ethereum/devp2p/)의 [DiscV4](https://github.com/ethereum/devp2p/blob/master/discv4.md)에선 노드가 가진 Public Key를 ID로 사용하고, 이를 통해 Distance를 구한다.
      ```
      distance(n₁, n₂) = keccak256(n₁) XOR keccak256(n₂)
      ```
      * libp2p에 좋은 transport 샘플들이 많음.

## TODO

- [x] libp2p Integration
- [x] Protobuf로 P2P Protocol Layer 구성
- [x] bootstrap 노드 데몬 구현
- [x] Sample Ping-pong node Test
