### ISSUE TITLE
App Manager

### ISSUE THREAD

**Issue by therne** [airbloc/airbloc-go#49]
**App Registry, without** 🥩

## Purpose

* 데이터 프로바이더 등록을 위한 API
* E2E 테스트를 보다 더 완전하게 완성
* 나중에 에어블록에서의 활동에 앱을 추가하기 위함

## Requirements

- [x] 앱 이름과 앱 설명을 통해 앱을 등록해야 함
  - 앱 설명은 MetaDB에 저장
- [x] 앱 정보를 가져올 수 있어야 함
- [x] 간단한 Create, Read API

## TODO (In the Next Phase)

- [ ] 더 많은 메타데이터 저장
    - 앱 아이콘 URL 저장
    - `appName`과 `displayName`을 구분함
    - 웹 서비스인 경우 도메인 저장
    - 앱인 경우 앱마켓 URL 저장
    - i18n에 대한 고려
    - IP 및 `Origin`에 대한 화이트리스트 저장
        - 이걸로 시빌어택을 막을 순 없지만, 프론트단에서 편리한 보안 기능을 제공합니다. `geth`의 Authentification 기능과 포지션이 유사할 수 있다고 생각하면 될 것 같습니다.
- [ ] 🥩

**Comment by therne** [comment]
Closed by #56, and will be continued on Phase 2 (#65).
