### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by therne** [airbloc/airbloc-go#88]
## Purpose

- Continuous Integration
- Full local environment testing
- Integration test / E2E test implementation

## TODO

- [ ] `Dockerfile`
- [ ] `docker-compose.yml`
- [ ] Update CircleCI configuration
- [ ] Push Docker image to [Docker Registry](https://docs.docker.com/registry/)
